### ISSUE TITLE
Online Demo Site

### ISSUE THREAD

**Issue by sudodaksh** [VPanjeta/ModiScript#15]
Hi, I just created a very basic (crappy really) but working website, that allows you to run modiscript code.

It is accessible on: https://modiscript.netlify.com/

PS: I know stdin doesn't work yet, i worked on it pretty late last night.

**Comment by onlinejudge95** [comment]
Can we have the output on a new line for `Scam.chai`

**Comment by sudodaksh** [comment]
Sure, give me sometime, I'll just refactor it in a few mins.

**Comment by sudodaksh** [comment]
PS: The only reason it's out right now is cuz I wanted to make it first.

**Comment by onlinejudge95** [comment]
GG dude

**Comment by abhyantrika** [comment]
Woah. Thanks guys.  Really appreciate this!
Maybe send a PR ?
We can merge the UI with the repo.

**Comment by sudodaksh** [comment]
I'm re-iterating upon it. I'll submit a pr asap ;)

**Comment by sudodaksh** [comment]
@abhyantrika @onlinejudge95 is there a way we can chat? It'll be easier instead of creating a giant trail of issue messages.

**Comment by onlinejudge95** [comment]
Ummm slack, anyone?

**Comment by sudodaksh** [comment]
Sure, telegram also works. Also can you review my pr, it standardizes the execution api.

**Comment by VPanjeta** [comment]
Seems pretty good.
Might seem pedantic but just one small detail, could you change the name of the second input field from `input` to something else that dictates it is a source code? 
`Input` sounds like it is expecting input from STDIN or a field where you give input to the program from.

**Comment by sudodaksh** [comment]
@VPanjeta actually the current version supports stdin, but it broke after you `relative imports bugs` commit, look at this:

```python
from modiscript.api import ModiScript
from modiscript.utils import ErrorHandler
```

```
File "web.py", line 3, in <module>
    from modiscript.api import ModiScript
  File "api.py", line 2, in <module>
    from parser import Parser
ImportError: cannot import name 'Parser' from 'parser'
```

**Comment by VPanjeta** [comment]
@DakshMiglani 
It had to be that way because relative imports won't work in case of running the file from outside the project folder. It will throw errors like this, which I suppose are because it is using relative imports in `in-package` import
```
Traceback (most recent call last):
  File "/home/vishal/Documents/shit/ModiScript/modiscript/MODI", line 8, in <module>
    from .utils import ErrorHandler, FNF, usage
ModuleNotFoundError: No module named '__main__.utils'; '__main__' is not a package
```

**Comment by sudodaksh** [comment]
Ahh okay, then I'd have to put the flask api into the `modiscript` directory

**Comment by TilakSN** [comment]
A better way would be to  move `MODI` (basically, the entrypoint) out of the package and let that import from package (specifically, `api`) and call relevant functions. Flask can then be a separate package which uses `api`.

**Comment by VPanjeta** [comment]
Moving `MODI` out of the package would mean keeping it in bin folder because that's how standards go for keeping source code. Which will again mess up imports if the `MODI` file is called from a directory that does not have the package in path.
The best way around it is to create a setup.py file for installation that moves the package to python lib and make all imports inside the package from `modiscript.`
For now, keeping a flask repo separate would be a good idea since this is the repo for source of modiscript and a web UI URL can be added in the README along with the link to the repo of the Web UI.

**Comment by sudodaksh** [comment]
> separate

That is what I was doing.

**Comment by sudodaksh** [comment]
Anyway, I'll send a pr for the setup.py and moving it into the bin directory.

**Comment by VPanjeta** [comment]
Ok. Wait on it. We'll discuss this and let you know. We're anyway not following community standards on anything else then I guess following those in project structure can also be ignored. So a simple api file could be accepted. Till then you can host the UI and keep its relevant code in your repo which can be linked the README file of this repo for trying out the web UI.

**Comment by sudodaksh** [comment]
But instead of adding an api file, can't we move the binary out of the library? That would you know fix the problem, and the library would work as-is. I'll still suggest making a package out of it.

**Comment by VPanjeta** [comment]
Yeah that's doable as well. Since we have decided not to follow the standards anyway, let's rebel against the community. Anyway, sorry for making you go through such a mess because of the standards and giving up on them at the last.
You can move the entry file out of the modiscript directory and add relative imports if it makes your flask api work but make sure the `MODI` file imports the `api` file and doesn't break in case `MODI` is called from some folder that doesn't have `modiscript` directory stored in it.
