### ISSUE TITLE
Support for windows ! 

### ISSUE THREAD

**Issue by LitHaxor** [VPanjeta/ModiScript#25]
In Linux it's showing error ! MODI Command not found . I've exported $path
**Also add support for poor windows nibbas**

**Comment by VPanjeta** [comment]
Hi @LitHaxor 

Can you provide the exact line for PATH that you're adding to your bashrc file so we can have a look and help you debug a little bit better? Also make sure the following steps are taken care of: 
1. Check if you have changed the path properly based on where the MODI file is located in your local machine.  
2. After doing the above, make sure you type `source ~/.bashrc` in any active terminal window open to reload path variable and try typing `MODI` then, otherwise it'll keep on working with the older PATH unless you restart your machine as PATH is only initialized on boot up.  
3. One more thing to keep in mind is, while initializing PATH environment variable, make sure `PATH` is in capital letters (I mean the environment variable name, as suggested in the installation steps), in some versions of Linux based OS' environment variables are case sensitive.


Coming to windows support, files were written keeping *nix OS systems in mind. It's doable on windows as well but you'll need to create batch files or convert the project to a windows executable. The former seems easier at this point but we don't have any plans to add support for windows for now. In any case, if someone can write batch files or compile the project into a windows executable then we'll happily accept PR for the same.

**Comment by LitHaxor** [comment]
![image](https://user-images.githubusercontent.com/30951672/85618782-20791a80-b683-11ea-8751-0e20c6eabdff.png)
I guess I did wrong to adding env path

**Comment by VPanjeta** [comment]
OK so it looks like you're adding the path stating that ModiScript folder is in root directory but I don't think that should be the case as most terminal windows open inside user `~` by default. So you can try the following steps and that should mostly fix the issue:
1. cd inside the ModiScript folder and type `ls`. Make sure `MODI` file is present in the result.
2. Type `pwd` (for Linux) to get the current working directory. It will most likely be of the format `/home/<username>/ModiScript` or `/home/<username>/folder1/folder2/ModiScript`
3. Copy the entire path in the result of the above command and paste it as a path to ModiScript in the bashrc file as `export PATH=$PATH:/home/<username>/ModiScript` and then save the file. Also the PATH environment variable should contain absolute paths, which is why we're adding the absolute path in this case.
4. Type `source ~/.bashrc` and type `MODI` to test.  

If you're still facing the same issue after these steps you can paste the result of `ls` inside ModiScript folder along with the result of `pwd` in the same folder and the path you added in bashrc after this. That will help us understand the issue better.
