### ISSUE TITLE
Windows: 'python3': permission denied error

### ISSUE THREAD

**Issue by AbdulMuhaymin** [VPanjeta/ModiScript#29]
![image](https://user-images.githubusercontent.com/62512971/86144067-dd44fe80-bafd-11ea-9827-9000ee323bbc.png)
Couldn't manage to run. I have also tried adding the export......... to the end of the /.bashrc file but still not working

**Comment by VPanjeta** [comment]
Hi @AbdulMuhaymin 

Looks like, you're trying to use this on Windows OS. Windows CMD isn't supported by default, but if you're trying to run it in windows bash then it might work.   

The first error that you see as "No such file or directory" is because `python3` is not in PATH. For windows you specifically need to add `python3` executable in PATH. Also check if windows installation of python 3 has executable named as `python` and not `python3`. If so, then rename the python executable.  

Coming to the "Permission Denied" error, that's happening because you're trying to execute the `python3` binary without having access to it. I would suggest you open the terminal in administrator mode or you can allow access to your current user for `python3` binary.

**Comment by AbdulMuhaymin** [comment]
Running in administrator mode fixed the issue
