### ISSUE TITLE
Publish this to PyPI

### ISSUE THREAD

**Issue by dvjn** [VPanjeta/ModiScript#34]
I think we can publish this as a library on `PyPI`, with a cli entry point

So people can directly do,
```shell
❯ pip install ModiScript
❯ MODI program.chai
```

Then even the website can be put into a separate repo, with `ModiScript` as a dependency.

I have some experience and I can set up a PR if you like the idea.

**Comment by VPanjeta** [comment]
Hi @divykj   

Thanks for the suggestion. Creating a .whl file is easy but it requires some time. Also given that the website is integrated on the API level and not cli level then that has to be changed as well. But since none of us are maintaining it regularly, we haven't gotten to doing it.  
We welcome any PRs regarding this scenario as long as it does not break any existing functionality. Creating a setup.py file would require the imports in the binary files also to be possibly changed accordingly maybe. 
Closing this issue for now as this is a feature request and nothing is to be tracked as the team isn't picking it up any time soon. Thanks again.

Regards
