### ISSUE TITLE
TypeError: required field "type_ignores" missing from Module

### ISSUE THREAD

**Issue by shridpant** [VPanjeta/ModiScript#37]
On executing .chai files with "MODI filename.chai", the following error is encountered:
<pre><font color="#4E9A06"><b>user@ubuntu</b></font>:<font color="#3465A4"><b>~/Documents/ModiScript/examples</b></font>$ MODI election.chai
Traceback (most recent call last):
  File &quot;/home/user/Documents/ModiScript/MODI&quot;, line 32, in &lt;module&gt;
    main()
  File &quot;/home/user/Documents/ModiScript/MODI&quot;, line 27, in main
    ms.execute(filename)
  File &quot;/home/user/Documents/ModiScript/modiscript/api.py&quot;, line 23, in execute
    ast_module = self._compile_file(value, value_type)
  File &quot;/home/user/Documents/ModiScript/modiscript/api.py&quot;, line 20, in _compile_file
    return compile(parse_out, &quot;&lt;ast&gt;&quot;, &quot;exec&quot;)
TypeError: required field &quot;type_ignores&quot; missing from Module
</pre>

<h3>Environment</h3>
OS: Ubuntu 20.04.1 LTS

Python: 3.8.2

**Comment by ayagrwl** [comment]
@shridpant How to solve this issue ?

**Comment by shridpant** [comment]
@ayagrwl Only faced this issue with **Python 3.8**. Seems to works just fine with lower versions of Python (>3).

**Comment by VPanjeta** [comment]
Hi @ayagrwl. 
It was caused because python 3.8 changed the way it compiles an abstract syntax tree using the standard ast library without any deprecation warning. The change was backwards incompatible and broke existing API. The solution would be to check for python version and update the ast compile methods in the code but since no one maintains the repository with current changes it would be better if you can just use python version 3.7 or lower if you wanna run it (maybe anaconda can help).
We're open to any contributions though for this fix. Should be a fairly simple fix with a version check and passing the parameters specific to the version to [this method](https://github.com/VPanjeta/ModiScript/blob/e6b6524bc000d276ff5429a45959af81c2b8d235/modiscript/api.py#L20).
Details of the change are mentioned out in [this bug report](https://bugs.python.org/issue35894) and they suggest doing the same solution (even though this technique is horrible to make the code work in all versions).
